# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81f24381cc32ed3f89a3e416844571f058460623d905d8fa9596938f014204e0aa5cbc5c026b24a04a70fc850323d49e85756235bf706828588a3e598da20177

test:
  secret_key_base: 5de5601e8285d4270e6d22cd4a6a75e9362712cdcf49da4983f1fb8b4983db80e26a04d3727888908130c9228c545908dff4b29dfec4322f382d2ee4dfbce956

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
